redirectsOrigin = "config"
plugins = []
functionsDirectory = "/home/runner/workspace/netlify-final-updated/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headers = []

[functions]

[functions."*"]

[build]
publish = "/home/runner/workspace/netlify-final-updated/dist/public"
publishOrigin = "config"
commandOrigin = "config"
base = "/home/runner/workspace/netlify-final-updated"
command = "npm install && npx vite build"
functions = "/home/runner/workspace/netlify-final-updated/netlify/functions"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]